import React from 'react';
import { Sparkles, AlertCircle } from 'lucide-react';
import { cn } from "@/lib/utils";

// Ensures all AI-generated content has clear indicators and ethical constraints
export default function EthicalAIWrapper({ children, type = 'suggestion', className }) {
  const config = {
    suggestion: {
      icon: Sparkles,
      label: 'AI-Generated Suggestion',
      bgColor: 'bg-purple-50',
      borderColor: 'border-purple-300',
      textColor: 'text-purple-700'
    },
    analysis: {
      icon: AlertCircle,
      label: 'AI-Generated Analysis',
      bgColor: 'bg-blue-50',
      borderColor: 'border-blue-300',
      textColor: 'text-blue-700'
    },
    prediction: {
      icon: AlertCircle,
      label: 'AI-Generated Estimate (Not Certainty)',
      bgColor: 'bg-orange-50',
      borderColor: 'border-orange-300',
      textColor: 'text-orange-700'
    }
  };

  const settings = config[type] || config.suggestion;
  const Icon = settings.icon;

  return (
    <div className={cn("space-y-3", className)}>
      {/* AI Indicator */}
      <div className={cn(
        "flex items-center gap-2 px-3 py-2 rounded-lg border-2 text-xs font-bold",
        settings.bgColor,
        settings.borderColor,
        settings.textColor
      )}>
        <Icon className="w-4 h-4" />
        <span>{settings.label}</span>
      </div>

      {/* Ethical Disclaimer */}
      <div className="p-3 bg-slate-50 border-2 border-slate-200 rounded-lg">
        <p className="text-xs text-slate-600 font-semibold">
          AI-generated — may be incomplete or inaccurate. ⚠️ This content was generated by AI and should be used as informational input only.
          It does not represent moral judgments, prescriptive actions, or certainty. 
          Always apply your own critical thinking and values.
        </p>
      </div>

      {/* Content */}
      <div>
        {children}
      </div>
    </div>
  );
}

// Utility to sanitize AI output - removes prescriptive/moral language
export const sanitizeAIOutput = (text) => {
  if (!text) return text;

  // Remove prescriptive language
  const prescriptivePatterns = [
    /you must/gi,
    /you should/gi,
    /you need to/gi,
    /it is imperative/gi,
    /the right thing to do/gi,
    /morally correct/gi,
    /ethically required/gi
  ];

  let sanitized = text;
  prescriptivePatterns.forEach(pattern => {
    sanitized = sanitized.replace(pattern, (match) => {
      // Replace with neutral alternatives
      if (match.toLowerCase().includes('must')) return 'you could consider';
      if (match.toLowerCase().includes('should')) return 'you might';
      if (match.toLowerCase().includes('need to')) return 'you could';
      return 'one option is';
    });
  });

  // Remove certainty language from predictions
  const certaintyPatterns = [
    /will definitely/gi,
    /guaranteed to/gi,
    /certainly will/gi,
    /without doubt/gi
  ];

  certaintyPatterns.forEach(pattern => {
    sanitized = sanitized.replace(pattern, () => {
      return 'may potentially';
    });
  });

  return sanitized;
};